/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneratorConfigMapLayer = t.iface([], {
  "name": "string",
  "dimensions": t.opt(t.iface([], {
    "width": "number",
    "height": "number",
  })),
  "position": t.opt(t.iface([], {
    "x": "number",
    "y": "number",
  })),
  "mapUnitDimensions": t.iface([], {
    "width": "number",
    "height": "number",
  }),
  "focus": t.opt(t.iface([], {
    "point": t.union(t.lit('system'), t.iface([], {
      "x": "number",
      "y": "number",
    })),
    "delta": t.opt(t.iface([], {
      "x": "number",
      "y": "number",
    })),
  })),
  "elements": t.iface([], {
    "systems": t.opt("boolean"),
    "systemLabels": t.opt("boolean"),
    "factions": t.opt(t.iface([], {
      "curveBorderEdges": t.opt("boolean"),
    })),
    "borderLabels": t.opt("boolean"),
    "jumpRings": t.opt(t.iface([], {
      "radii": t.array("number"),
      "delta": t.opt(t.iface([], {
        "x": "number",
        "y": "number",
      })),
    })),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneratorConfigMapLayer,
};
export default exportedTypeSuite;
