/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GeneratorConfig = t.iface([], {
  "output": t.lit('svg'),
  "theme": t.opt(t.union(t.lit('light'), t.lit('dark'))),
  "fileOutput": t.iface([], {
    "directory": "string",
    "fileNamePattern": "string",
  }),
  "eras": t.opt(t.array("number")),
  "iterateObjects": t.opt(t.iface([], {
    "type": t.lit('system'),
    "pattern": t.opt("string"),
  })),
  "dimensions": t.iface([], {
    "width": "number",
    "height": "number",
  }),
  "mapLayers": t.array("GeneratorConfigMapLayer"),
  "overlays": t.opt(t.array("GeneratorConfigOverlay")),
});

const exportedTypeSuite: t.ITypeSuite = {
  GeneratorConfig,
};
export default exportedTypeSuite;
