env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-use-before-define': off
  # lines-between-class-members: off
  # '@typescript-eslint/lines-between-class-members': off
  # linebreak-style: off
  # no-plusplus: off
  array-bracket-spacing: [error, never]
  computed-property-spacing: [error, never]
  eol-last: [warn, always]
  no-param-reassign: error
  object-curly-newline: [error, { multiline: true }]
  object-curly-spacing: [error, always]
  quote-props: [error, consistent]
  semi: [warn, always, { omitLastInOneLineBlock: true }]
  space-in-parens: [error, never]
