# TODO add documentation on what the different parameters mean, and what the valid values are
rules:
  distanceBetweenCandidates: 3 # 6 # 12 # 7.5 seems to be a good value
  labelDistanceToBorder: 1.25
  maxLabelOverlapArea: 24
  borderIntersectionTolerance: 0.25
  maxBorderIntersectionDistance: 2.5
  minDistanceBetweenLabels: 40
  minLoopDistanceBetweenLabels: 55
  cornerDistanceFactor: .05
  minViableScore: .65
  minGoodScore: .75

scoreWeights:
  labelOverlap: 115
  angle: 10
  borderIntersection: 50
  centeredness: 0
  cornerScore: 50
  multiline: 30
  straightness: 45

manualConfigs:
  CS:
    - anchor:
        x: 2
        y: -4
      eras: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
