# TODO add documentation on what the different parameters mean, and what the valid values are
rules:
  distanceBetweenCandidates: 3 # 6 # 12 # 7.5 seems to be a good value
  labelDistanceToBorder: 1.25
  maxLabelOverlapArea: 24
  borderIntersectionTolerance: 0.25
  maxBorderIntersectionDistance: 3
  minDistanceBetweenLabels: 40
  minLoopDistanceBetweenLabels: 55
  minViableScore: .6

scoreWeights:
  labelOverlap: 100
  angle: 10
  borderIntersection: 50
  centeredness: 15
  multiline: 10
  straightness: 40

manualConfigs:
  CS:
    - anchor:
        x: 2
        y: -4
      eras: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
