# TODO add documentation on what the different parameters mean, and what the valid values are
rules:
  distanceBetweenCandidates: 12 # 7.5 seems to be a good value
  labelDistanceToBorder: 1.25
  maxLabelOverlapArea: 24
  borderIntersectionTolerance: 0.25
  maxBorderIntersectionDistance: 5
  minDistanceBetweenLabels: 40
  minLoopDistanceBetweenLabels: 55
  minViableScore: .65

scoreWeights:
  labelOverlap: 100
  angle: 10
  borderIntersection: 50
  centeredness: 15
  multiline: 10
  straightness: 20

manualConfigs:
  CS:
    - anchor:
        x: 2
        y: -4
      eras: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
