output: svg # only svg available at the moment
theme: dark # color theme (light or dark)

debugMode: false

fileOutput:
  directory: './out'
  fileNamePattern: 'Battletech Inner Sphere_{{ERAYEAR}}_{{ERANAME}}.dark.svg' # SYSTEMINDEX, SYSTEMID, SYSTEMNAME, ERAINDEX, ERAID, ERAYEAR, ERANAME

eras: # the eras to create images for - either a list of era indices (0-based), or empty for all eras
  - 30 # 3059d

dimensions: # output image pixel size
  width: 1450
  height: 1200

mapLayers: # the different layers showing maps
  - name: basemap # basemap layer
    mapUnitDimensions: # dimensions of the basemap (in map units)
      width: 1450
      height: 1200
    focus: # the focus point of the main map (in map units)
      point:
        x: 75
        y: -30
    elements:
      systems: true # display systems (as dots)
      systemLabels: true # display system names
      borders:
        - display: factions # first-level (faction) borders
          curveBorderEdges: true
          borderLabels: true # display border labels

overlays: # other items on top of the map layers
  - name: main-map-scale
    type: scale # a scale displaying the relation of pixels to map units
    attributes:
      pixelsPerMapUnit: 1
      max: 500 # maximum unit shown
      step: 100 # color change after this many units
      scaleHeight: 12
      labelsPosition: below
    position: # the scale's pixel position (top left point of the scale bar)
      x: 900
      y: 1140
  - name: main-map-scale-frame
    type: rectangle
    attributes:
      width: 500
      height: 12
      strokeWidth: 3
    position:
      x: 900
      y: 1140

