output: svg # only svg available at the moment
theme: light # color theme (light or dark)

debugMode: true

fileOutput:
  directory: './out'
  fileNamePattern: 'Battletech Inner Sphere_{{ERAYEAR}}_{{ERANAME}}.svg' # SYSTEMINDEX, SYSTEMID, SYSTEMNAME, ERAINDEX, ERAID, ERAYEAR, ERANAME

eras: # the eras to create images for - either a list of era indices (0-based), or empty for all eras
  - 16 # 3025
  #- 20 # 3050
  #- 30 # 3059d
  #- 38 # 3095

dimensions: # output image pixel size
  width: 1450
  height: 1200

mapLayers: # the different layers showing maps
  - name: basemap # basemap layer
    mapUnitDimensions: # dimensions of the basemap (in map units)
      width: 1450
      height: 1200
    focus: # the focus point of the main map (in map units)
      point:
        x: 75
        y: -30
    elements:
      systems: true # display systems (as dots)
      systemLabels: true # display system names
      borders:
        - display: factions # first-level (faction) borders
          curveBorderEdges: true
          borderLabels: true # display border labels
        - display: regions # second-level (state/province) borders
          curveBorderEdges: true
        - display: regions # third-level (state/province) borders
          curveBorderEdges: true

