output: svg # only svg available at the moment
theme: light # color theme (only light theme available at the moment)

fileOutput:
  directory: './out'
  fileNamePattern: 'Battletech Universe_{{ERAYEAR}}_{{ERANAME}}.svg' # SYSTEMINDEX, SYSTEMID, SYSTEMNAME, ERAINDEX, ERAID, ERAYEAR, ERANAME

#eras: # the eras to create images for - either a list of era indices (0-based), or empty for all eras
  #  - 16 # 3025
#  - 20 # 3050

dimensions: # output image pixel size
  width: 4000
  height: 4000

mapLayers: # the different layers showing maps
  - name: basemap # basemap layer
    mapUnitDimensions: # dimensions of the basemap (in map units)
      width: 4000
      height: 4000
    focus: # the focus point of the main map (in map units)
      point:
        x: 0
        y: 0
    elements:
      systems: true # display systems (as dots)
      systemLabels: true # display system names
      borders:
        - display: factions # first-level (faction) borders
          curveBorderEdges: true
          borderLabels: true # display border labels
      borderLabels: true # display border labels

overlays: # other items on top of the map layers
  #- type: text # map title
  #  attributes: # attributes specific to this type of overlay
  #    text: '?'

  - name: sarna-logo
    type: svgElement # the sarna logo svg paths
    attributes: # attributes specific to this type of overlay
      cssTemplate: sarna-logo.css.tpl
      svgTemplate: sarna-logo.svg.tpl
      scale: 1.5
    position: # the logo's pixel position (top left point)
      x: 10
      y: 10
  - name: main-map-scale
    type: scale # a scale displaying the relation of pixels to map units
    attributes:
      pixelsPerMapUnit: 1
      max: 500 # maximum unit shown
      step: 100 # color change after this many units
      scaleHeight: 26
      labelsPosition: below
    position: # the scale's pixel position (top left point of the scale bar)
      x: 160
      y: 10 # 1143 - 11 - 10
  - name: main-map-scale-frame
    type: rectangle
    attributes:
      width: 500
      height: 26
      strokeWidth: 3
    position:
      x: 160
      y: 10

